def safe_money(val):
    """Return formatted money or N/A if the value is invalid."""
    try:
        return f"${float(val):.2f}"
    except Exception:
        return "N/A"


def safe_text(val):
    """Return text or N/A if None or empty."""
    return val if val not in (None, "", "None") else "N/A"


def get_invoice_html(invoice: dict, summary: dict) -> str:
    """
    HTML email renderer.
    Uses LLM summary + invoice data.
    """

    severity_color = {
        "Low": "#28a745",
        "Medium": "#ffc107",
        "High": "#dc3545",
    }.get(summary.get("severity"), "#6c757d")

    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; background:#f6f6f6; padding:20px;">
      <div style="max-width:700px; margin:auto; background:#ffffff; padding:20px; border-radius:8px;">

        <h2 style="background:#2c3e50; color:white; padding:15px; border-radius:6px;">
          Invoice Approval Required
        </h2>

        <div style="background:#f8d7da; padding:15px; border-radius:6px; margin-top:15px;">
          <p><b>Anomaly:</b> {summary.get("anomaly_one_line")}</p>
          <p><b>Recommendation:</b> {summary.get("recommendation")}</p>
        </div>

        <hr>

        <p><b>Vendor:</b> {invoice.get("vendor", "N/A")}</p>
        <p><b>Invoice No:</b> {invoice.get("invoice_no", "N/A")}</p>
        <p><b>Invoice Date:</b> {invoice.get("invoice_date", "N/A")}</p>

        <p>
          <b>Severity:</b>
          <span style="color:white; background:{severity_color}; padding:4px 10px; border-radius:12px;">
            {summary.get("severity")} ({summary.get("confidence")}%)
          </span>
        </p>

        <hr>

        <h4>Items</h4>
        <table width="100%" border="1" cellspacing="0" cellpadding="6">
          <tr style="background:#efefef;">
            <th>Item</th>
            <th>Qty</th>
            <th>Unit</th>
            <th>Unit Price</th>
            <th>Total</th>
          </tr>
          {
            "".join(
                f"<tr>"
                f"<td>{i.get('material_name')}</td>"
                f"<td>{i.get('quantity')}</td>"
                f"<td>{i.get('unit')}</td>"
                f"<td>{i.get('unit_price')}</td>"
                f"<td>{i.get('line_total')}</td>"
                f"</tr>"
                for i in invoice.get("items", [])
            )
          }
        </table>

        <hr>

        <p style="font-size:12px; color:#777;">
          Generated by Invoice Agent Automated System
        </p>

      </div>
    </body>
    </html>
    """
